
-- All roles
INSERT INTO REG_ROLE (REG_ROLE_ID, ROLE_NAME, ROLE_DESC, ACTIVE_FLG) VALUES (1, 'ADMIN', 'Admin role for high level access', TRUE);
INSERT INTO REG_ROLE (REG_ROLE_ID, ROLE_NAME, ROLE_DESC, ACTIVE_FLG) VALUES (2, 'USER', 'Regular role for basic access', TRUE);

INSERT INTO REGISTRATION (FIRST_NAME, LAST_NAME, CONTACT_EMAIL, PASSWORD, ACTIVE_FLG, DELETE_FLG, CREATED_DT, CREATED_USER, MODIFIED_DT, MODIFIED_USER) 
VALUES ('HRM', 'Admin', 'administrator@hrm.com', '{bcrypt}$2a$10$Cm34YVFsO4pEwmkVbIRCqu36uYcQdg3Q8sNR1dXMTjJrGCp8DqakC', TRUE, FALSE, current_timestamp, 'SYSTEM', current_timestamp, 'SYSTEM');
INSERT INTO REG_USER_ROLE_MAP (REG_ROLE_ID, REGISTRATION_ID) SELECT 1, REGISTRATION_ID FROM REGISTRATION WHERE CONTACT_EMAIL = 'administrator@bm.com';
