
-- Basic config data
INSERT INTO CONFIG (CONFIG_ID,CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,ACTIVE_FLG) VALUES (1,'CONTEXT_PATH','http://localhost:8080/hrm',null,'Y');
INSERT INTO CONFIG (CONFIG_ID,CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,ACTIVE_FLG) VALUES (2,'CONTEXT_ROOT','hrm',null,'Y');
INSERT INTO CONFIG (CONFIG_ID,CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,ACTIVE_FLG) VALUES (3,'FROM-ADDRESS','revenue.hr.mgmt@gmail.com',null,'Y');
INSERT INTO CONFIG (CONFIG_ID,CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,ACTIVE_FLG) VALUES (4,'GMAIL_USERNAME','revenue.hr.mgmt',null,'Y');
INSERT INTO CONFIG (CONFIG_ID,CONFIG_KEY,CONFIG_VALUE,DESCRIPTION,ACTIVE_FLG) VALUES (5,'GMAIL-PASSWORD','Scu@hrm01',null,'Y');

-- All roles
INSERT INTO REG_ROLE (REG_ROLE_ID, ROLE_NAME, ROLE_DESC, ACTIVE_FLG) VALUES (2, 'USER', 'Regular role for basic access', TRUE);
