
CREATE TABLE REGISTRATION
(
   	REGISTRATION_ID 			serial,
   	REG_BUDGET_MAP_ID			integer,
   	FIRST_NAME					varchar(50),
   	LAST_NAME					varchar(50),
   	CONTACT_EMAIL 				varchar(50),
   	MOBILE_NUMBER				varchar(10),
   	PASSWORD 					varchar(100),
   	ACTIVE_FLG 					boolean,
   	DELETE_FLG 					boolean,
   	CREATED_DT       			timestamp with time zone,
   	CREATED_USER   				varchar(50),
   	MODIFIED_DT 				timestamp with time zone,
   	MODIFIED_USER   			varchar(50)
);
ALTER TABLE REGISTRATION ADD CONSTRAINT PK_REGISTRATION PRIMARY KEY (REGISTRATION_ID);
ALTER TABLE REGISTRATION ADD CONSTRAINT UC_CONTACT_EMAIL UNIQUE (CONTACT_EMAIL);
ALTER TABLE REGISTRATION ADD CONSTRAINT FK_REG_BUDGET_MAP_ID FOREIGN KEY (REG_BUDGET_MAP_ID) REFERENCES REG_BUDGET_MAP (REG_BUDGET_MAP_ID);


CREATE TABLE REG_USER_LOGIN_H
(
   	REG_USER_LOGIN_H_ID 		serial,
   	FIRST_NAME					varchar(50),
   	LAST_NAME					varchar(50),
   	CONTACT_EMAIL 				varchar(50),
   	MOBILE_NUMBER				varchar(13),
   	LOGIN_DT					timestamp with time zone,
   	REGISTRATION_ID 			integer
);
ALTER TABLE REG_USER_LOGIN_H ADD CONSTRAINT PK_REG_USER_LOGIN_H PRIMARY KEY (REG_USER_LOGIN_H_ID);
ALTER TABLE REG_USER_LOGIN_H ADD CONSTRAINT FK_REG_LOGIN_H_USER_ID FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION (REGISTRATION_ID);

CREATE TABLE REG_ROLE
(
  	REG_ROLE_ID 				integer,
   	ROLE_NAME 					varchar(50),
   	ROLE_DESC					varchar(100),
   	ACTIVE_FLG 					boolean
);
ALTER TABLE REG_ROLE ADD CONSTRAINT PK_REG_ROLE PRIMARY KEY (REG_ROLE_ID);
ALTER TABLE REG_ROLE ADD CONSTRAINT UC_ROLE_NAME UNIQUE (ROLE_NAME);


CREATE TABLE REG_USER_ROLE_MAP
(
   	REG_USER_ROLE_MAP_ID 		serial,
   	REG_ROLE_ID 				integer,
   	REGISTRATION_ID 			integer
);
ALTER TABLE REG_USER_ROLE_MAP ADD CONSTRAINT PK_REG_USER_ROLE_MAP PRIMARY KEY (REG_USER_ROLE_MAP_ID);
ALTER TABLE REG_USER_ROLE_MAP ADD CONSTRAINT FK_ROLE_MAP_REG_ROLE_ID FOREIGN KEY (REG_ROLE_ID) REFERENCES REG_ROLE (REG_ROLE_ID);
ALTER TABLE REG_USER_ROLE_MAP ADD CONSTRAINT FK_ROLE_MAP_REGISTRATION_ID FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION (REGISTRATION_ID);


CREATE TABLE REG_BUDGET_MAP
(
	REG_BUDGET_MAP_ID			serial,
	CREATED_DT       			timestamp with time zone,
   	CREATED_USER   				varchar(50)
);
ALTER TABLE REG_BUDGET_MAP ADD CONSTRAINT PK_REG_BUDGET_MAP PRIMARY KEY (REG_BUDGET_MAP_ID);


CREATE TABLE BUDGET
(
	BUDGET_ID					serial,
	REG_BUDGET_MAP_ID			integer,
	DESCRIPTION					varchar(200),
	CREATED_DT       			timestamp with time zone,
   	CREATED_USER   				varchar(50),
   	MODIFIED_DT 				timestamp with time zone,
   	MODIFIED_USER   			varchar(50)
);
ALTER TABLE BUDGET ADD CONSTRAINT PK_BUDGET PRIMARY KEY (BUDGET_ID);
ALTER TABLE BUDGET ADD CONSTRAINT FK_BUDGET_REG_BUDGET_MAP_ID FOREIGN KEY (REG_BUDGET_MAP_ID) REFERENCES REG_BUDGET_MAP (REG_BUDGET_MAP_ID);


CREATE TABLE BUDGET_DETAILS
(
	BUDGET_DETAILS_ID			serial,
	BUDGET_ID					integer,
	REGISTRATION_ID 			integer
);
ALTER TABLE BUDGET_DETAILS ADD CONSTRAINT PK_BUDGET_DETAILS PRIMARY KEY (BUDGET_DETAILS_ID);
ALTER TABLE BUDGET_DETAILS ADD CONSTRAINT FK_BUDGET_ID FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET (BUDGET_ID);
ALTER TABLE BUDGET_DETAILS ADD CONSTRAINT FK_REGISTRATION_ID FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION (REGISTRATION_ID);




