

CREATE TABLE CONFIG 
(
	CONFIG_ID 				SERIAL,
	CONFIG_KEY 				VARCHAR2 (100),
	CONFIG_VALUE 			VARCHAR2 (100),
	DESCRIPTION 			VARCHAR2 (100),
	ACTIVE_FLG 				CHAR(1)
);
ALTER TABLE CONFIG ADD CONSTRAINT PK_CONFIG PRIMARY KEY (CONFIG_ID);


CREATE TABLE REGISTRATION
(
   	REGISTRATION_ID 			SERIAL,
   	REG_BUDGET_MAP_ID			INTEGER,
   	FIRST_NAME					VARCHAR2 (50),
   	LAST_NAME					VARCHAR2 (50),
   	CONTACT_EMAIL 				VARCHAR2 (50),
   	MOBILE_NUMBER				VARCHAR2 (10),
   	PASSWORD 					VARCHAR2 (100),
   	ACTIVE_FLG 					BOOLEAN,
   	DELETE_FLG 					BOOLEAN,
   	CREATED_DT       			TIMESTAMP WITH TIME ZONE,
   	CREATED_USER   				VARCHAR2 (50),
   	MODIFIED_DT 				TIMESTAMP WITH TIME ZONE,
   	MODIFIED_USER   			VARCHAR2 (50)
);
ALTER TABLE REGISTRATION ADD CONSTRAINT PK_REGISTRATION PRIMARY KEY (REGISTRATION_ID);
ALTER TABLE REGISTRATION ADD CONSTRAINT UC_CONTACT_EMAIL UNIQUE (CONTACT_EMAIL);
ALTER TABLE REGISTRATION ADD CONSTRAINT FK_REG_BUDGET_MAP_ID FOREIGN KEY (REG_BUDGET_MAP_ID) REFERENCES REG_BUDGET_MAP (REG_BUDGET_MAP_ID);


CREATE TABLE REG_USER_LOGIN_H
(
   	REG_USER_LOGIN_H_ID 		SERIAL,
   	FIRST_NAME					VARCHAR2 (50),
   	LAST_NAME					VARCHAR2 (50),
   	CONTACT_EMAIL 				VARCHAR2 (50),
   	MOBILE_NUMBER				VARCHAR2 (13),
   	LOGIN_DT					TIMESTAMP WITH TIME ZONE,
   	REGISTRATION_ID 			INTEGER
);
ALTER TABLE REG_USER_LOGIN_H ADD CONSTRAINT PK_REG_USER_LOGIN_H PRIMARY KEY (REG_USER_LOGIN_H_ID);
ALTER TABLE REG_USER_LOGIN_H ADD CONSTRAINT FK_REG_LOGIN_H_USER_ID FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION (REGISTRATION_ID);


CREATE TABLE REG_ROLE
(
  	REG_ROLE_ID 				INTEGER,
   	ROLE_NAME 					VARCHAR2 (50),
   	ROLE_DESC					VARCHAR2 (100),
   	ACTIVE_FLG 					boolean
);
ALTER TABLE REG_ROLE ADD CONSTRAINT PK_REG_ROLE PRIMARY KEY (REG_ROLE_ID);
ALTER TABLE REG_ROLE ADD CONSTRAINT UC_ROLE_NAME UNIQUE (ROLE_NAME);


CREATE TABLE REG_USER_ROLE_MAP
(
   	REG_USER_ROLE_MAP_ID 		SERIAL,
   	REG_ROLE_ID 				INTEGER,
   	REGISTRATION_ID 			INTEGER
);
ALTER TABLE REG_USER_ROLE_MAP ADD CONSTRAINT PK_REG_USER_ROLE_MAP PRIMARY KEY (REG_USER_ROLE_MAP_ID);
ALTER TABLE REG_USER_ROLE_MAP ADD CONSTRAINT FK_ROLE_MAP_REG_ROLE_ID FOREIGN KEY (REG_ROLE_ID) REFERENCES REG_ROLE (REG_ROLE_ID);
ALTER TABLE REG_USER_ROLE_MAP ADD CONSTRAINT FK_ROLE_MAP_REGISTRATION_ID FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION (REGISTRATION_ID);


CREATE TABLE REG_BUDGET_MAP
(
	REG_BUDGET_MAP_ID			SERIAL,
	CREATED_DT       			TIMESTAMP WITH TIME ZONE,
   	CREATED_USER   				VARCHAR2 (50)
);
ALTER TABLE REG_BUDGET_MAP ADD CONSTRAINT PK_REG_BUDGET_MAP PRIMARY KEY (REG_BUDGET_MAP_ID);


CREATE TABLE BUDGET
(
	BUDGET_ID					SERIAL,
	REG_BUDGET_MAP_ID			INTEGER,
	DESCRIPTION					VARCHAR2 (200),
	ACTIVE_FLG					BOOLEAN,
	DELETE_FLG					BOOLEAN,
	CREATED_DT       			TIMESTAMP WITH TIME ZONE,
   	CREATED_USER   				VARCHAR2 (50),
   	MODIFIED_DT 				TIMESTAMP WITH TIME ZONE,
   	MODIFIED_USER   			VARCHAR2 (50)
);
ALTER TABLE BUDGET ADD CONSTRAINT PK_BUDGET PRIMARY KEY (BUDGET_ID);
ALTER TABLE BUDGET ADD CONSTRAINT FK_BUDGET_REG_BUDGET_MAP_ID FOREIGN KEY (REG_BUDGET_MAP_ID) REFERENCES REG_BUDGET_MAP (REG_BUDGET_MAP_ID);


CREATE TABLE BUDGET_DETAILS
(
	BUDGET_DETAILS_ID			SERIAL,
	BUDGET_ID					INTEGER,
	REGISTRATION_ID 			INTEGER
);
ALTER TABLE BUDGET_DETAILS ADD CONSTRAINT PK_BUDGET_DETAILS PRIMARY KEY (BUDGET_DETAILS_ID);
ALTER TABLE BUDGET_DETAILS ADD CONSTRAINT FK_BUDGET_ID FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET (BUDGET_ID);
ALTER TABLE BUDGET_DETAILS ADD CONSTRAINT FK_REGISTRATION_ID FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATION (REGISTRATION_ID);


CREATE TABLE WORK_SCHEDULE
(
	WORK_SCHEDULE_ID					SERIAL,
	REG_BUDGET_MAP_ID			INTEGER,
	SCHEDULE_CANDIDATE			VARCHAR2 (50),
	SCHEDULE_WORK				VARCHAR2 (200),
	SCHEDULE_DATE				TIMESTAMP WITH TIME ZONE,
	DELETE_FLG					BOOLEAN,
	CREATED_DT       			TIMESTAMP WITH TIME ZONE,
   	CREATED_USER   				VARCHAR2 (50),
   	MODIFIED_DT 				TIMESTAMP WITH TIME ZONE,
   	MODIFIED_USER   			VARCHAR2 (50)
);
ALTER TABLE WORK_SCHEDULE ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY (WORK_SCHEDULE_ID);
ALTER TABLE WORK_SCHEDULE ADD CONSTRAINT FK_WORK_SCHEDULE_REG_BUDGET_MAP_ID FOREIGN KEY (REG_BUDGET_MAP_ID) REFERENCES REG_BUDGET_MAP (REG_BUDGET_MAP_ID);


