
DROP TABLE if exists REG_USER_LOGIN_H;
DROP TABLE if exists REG_USER_ROLE_MAP;
DROP TABLE if exists BUDGET_DETAILS;
DROP TABLE if exists REGISTRATION;
DROP TABLE if exists REG_ROLE;
DROP TABLE if exists BUDGET;
DROP TABLE if exists REG_BUDGET_MAP;
