
DROP TABLE IF EXISTS REG_USER_LOGIN_H;
DROP TABLE IF EXISTS REG_USER_ROLE_MAP;
DROP TABLE IF EXISTS BUDGET_DETAILS;
DROP TABLE IF EXISTS REGISTRATION;
DROP TABLE IF EXISTS REG_ROLE;
DROP TABLE IF EXISTS BUDGET;
DROP TABLE IF EXISTS REG_BUDGET_MAP;
DROP TABLE IF EXISTS SCHEDULE;
